#!/usr/bin/env node
// Regenerates data/geo/us-ct.json — the Connecticut county outlines the region
// map draws, pre-projected to SVG path data so the site needs no mapping
// library and no third-party tile request at view time.
//
// Source geometry: US Census Bureau cartographic boundary files (2018 county
// generalisation), which are US Government works in the public domain. CT
// replaced counties with planning regions as county-equivalents in 2022; the
// legacy eight counties are kept deliberately because that is what the public,
// and every record in data/spaces, still uses.
//
// Run:  node scripts/build-geo.mjs   (needs network; output is committed)
import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const SRC = 'https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json';
const STATE = '09';
const WIDTH = 1000;
const PAD = 12;
const TOLERANCE = 0.0016; // degrees — Douglas-Peucker, tuned so CT keeps its shape at ~1000px

/** Perpendicular distance simplification. The outlines are decoration at
 *  ~1000px wide; full census detail would be an order of magnitude more bytes
 *  for pixels nobody can see. */
function simplify(points, tol) {
  if (points.length < 3) return points;
  const sq = tol * tol;
  const d2 = ([px, py], [ax, ay], [bx, by]) => {
    let x = ax, y = ay, dx = bx - ax, dy = by - ay;
    if (dx || dy) {
      const t = ((px - ax) * dx + (py - ay) * dy) / (dx * dx + dy * dy);
      if (t > 1) { x = bx; y = by; } else if (t > 0) { x += dx * t; y += dy * t; }
    }
    return (px - x) ** 2 + (py - y) ** 2;
  };
  const keep = new Uint8Array(points.length);
  keep[0] = keep[points.length - 1] = 1;
  const stack = [[0, points.length - 1]];
  while (stack.length) {
    const [first, last] = stack.pop();
    let index = -1, max = sq;
    for (let i = first + 1; i < last; i++) {
      const d = d2(points[i], points[first], points[last]);
      if (d > max) { index = i; max = d; }
    }
    if (index > 0) { keep[index] = 1; stack.push([first, index], [index, last]); }
  }
  return points.filter((_, i) => keep[i]);
}

const res = await fetch(SRC);
if (!res.ok) throw new Error(`${SRC} → ${res.status}`);
const all = await res.json();

const features = all.features.filter((f) => f.properties?.STATE === STATE);
if (features.length !== 8) throw new Error(`expected 8 CT counties, got ${features.length}`);

const rings = (g) => (g.type === 'Polygon' ? [g.coordinates] : g.coordinates).flat();

// Equirectangular, scaled at CT's mid-latitude. At this extent the distortion
// against a proper conic is well under a pixel, and it keeps the forward
// projection a two-line function the component can reuse for pins.
const pts = features.flatMap((f) => rings(f.geometry).flat());
const lons = pts.map((p) => p[0]), lats = pts.map((p) => p[1]);
const [minLon, maxLon] = [Math.min(...lons), Math.max(...lons)];
const [minLat, maxLat] = [Math.min(...lats), Math.max(...lats)];
const lat0 = (minLat + maxLat) / 2;
const kx = Math.cos((lat0 * Math.PI) / 180);
const k = (WIDTH - PAD * 2) / ((maxLon - minLon) * kx);
const height = Math.round((maxLat - minLat) * k + PAD * 2);

const project = ([lon, lat]) => [
  +(PAD + (lon - minLon) * kx * k).toFixed(1),
  +(PAD + (maxLat - lat) * k).toFixed(1),
];

/** Area-weighted centroid of the largest ring, so a county's name sits inside
 *  its own shape rather than in the middle of its bounding box. */
function centroid(ring) {
  let a = 0, cx = 0, cy = 0;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const f = ring[j][0] * ring[i][1] - ring[i][0] * ring[j][1];
    a += f;
    cx += (ring[j][0] + ring[i][0]) * f;
    cy += (ring[j][1] + ring[i][1]) * f;
  }
  return a ? [+(cx / (3 * a)).toFixed(1), +(cy / (3 * a)).toFixed(1)]
           : [ring[0][0], ring[0][1]];
}

const counties = features
  .map((f) => {
    const projected = rings(f.geometry)
      .map((ring) => simplify(ring, TOLERANCE).map(project))
      .filter((ring) => ring.length > 2);
    const biggest = projected.reduce((a, b) => (b.length > a.length ? b : a), projected[0]);
    return {
      name: f.properties.NAME,
      fips: f.id ?? f.properties.GEOID,
      label: centroid(biggest),
      d: projected.map((ring) => `M${ring.map((p) => p.join(',')).join('L')}Z`).join(''),
    };
  })
  .sort((a, b) => a.name.localeCompare(b.name));

const out = {
  $comment:
    'Generated by scripts/build-geo.mjs — do not edit by hand. Census Bureau ' +
    'cartographic boundaries (public domain), simplified and pre-projected.',
  source: { system: 'us_census', url: SRC, license: 'public domain (US Government work)' },
  viewBox: `0 0 ${WIDTH} ${height}`,
  // Everything the component needs to place a space's lat/lon in the same frame.
  projection: { minLon, maxLat, kx: +kx.toFixed(8), k: +k.toFixed(4), pad: PAD },
  counties,
};

const path = join(dirname(fileURLToPath(import.meta.url)), '../data/geo/us-ct.json');
writeFileSync(path, JSON.stringify(out, null, 2) + '\n');
console.log(`wrote ${path} — ${counties.length} counties, viewBox ${out.viewBox}, ` +
            `${Math.round(JSON.stringify(out).length / 1024)}KB`);
